from .sdfa_method import SDFA


class DFA(SDFA):
    def __init__(
            self, total_models_dict: dict, connectivity_dict=None,
            seg_sending_num=7, largest_seg_num=10, aggregating_seg_threshold=5,
            parameter_scope="all",
            segment_unit="parameter",
            block_grouping_method="none",
            block_group_size=1,
            channel_length=0,
            block_refinement=None,
            aggregation_score_source="uniform",
            fisher_block=False,
            include_other_blocks=False,
            bn_mode="affine",
            bn_process_as_base_unit=True,
            bn_aggregation_source="score",
            segment_importance_metric="weight_abs",
            importance_parameter_to_unit="mean_abs",
            importance_unit_to_group="mean",
            importance_group_to_segment="mean",
            importance_lipschitz_ema_enabled=False,
            group_enabled=False,
            group_criterion_metric="gradient_abs_ema_online",
            group_criterion_parameter_to_unit="mean_abs",
            group_criterion_lipschitz_ema_enabled=False,
            segment_compose_method="score_sorted_balanced_payload",
            segment_pick_exp_normalize=True,
            segment_pick_exp_base=None,
            recipient_pick_method="uniform_with_replacement",
            recipient_balance_strength=1.0,
            **_
    ):
        super().__init__(
            total_models_dict=total_models_dict,
            seg_divided_number=1,
            connectivity_dict=connectivity_dict,
            seg_create_method="consistent",
            seg_chosen_method="uniform",
            seg_sending_num=seg_sending_num,
            largest_seg_num=largest_seg_num,
            aggregating_seg_threshold=aggregating_seg_threshold,
            parameter_scope=parameter_scope,
            segment_unit=segment_unit,
            block_grouping_method=block_grouping_method,
            block_group_size=block_group_size,
            channel_length=channel_length,
            block_refinement=block_refinement,
            aggregation_score_source=aggregation_score_source,
            fisher_block=fisher_block,
            include_other_blocks=include_other_blocks,
            bn_mode=bn_mode,
            bn_process_as_base_unit=bn_process_as_base_unit,
            bn_aggregation_source=bn_aggregation_source,
            segment_importance_metric=segment_importance_metric,
            importance_parameter_to_unit=importance_parameter_to_unit,
            importance_unit_to_group=importance_unit_to_group,
            importance_group_to_segment=importance_group_to_segment,
            importance_lipschitz_ema_enabled=importance_lipschitz_ema_enabled,
            group_enabled=group_enabled,
            group_criterion_metric=group_criterion_metric,
            group_criterion_parameter_to_unit=group_criterion_parameter_to_unit,
            group_criterion_lipschitz_ema_enabled=group_criterion_lipschitz_ema_enabled,
            segment_compose_method=segment_compose_method,
            segment_pick_exp_normalize=segment_pick_exp_normalize,
            segment_pick_exp_base=segment_pick_exp_base,
            recipient_pick_method=recipient_pick_method,
            recipient_balance_strength=recipient_balance_strength,
        )
